version: "3.9"

services:

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bookmark_service
      POSTGRES_PASSWORD: bookmark_service

  webpack:
    build: .
    command: ./bin/webpack-dev-server
    container_name: webpack
    volumes:
      - .:/bookmark_service
    ports:
      - "3035:3035"
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  bookmark_service:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: bookmark_service
    tty: true
    stdin_open: true
    volumes:
      - .:/bookmark_service
    ports:
      - "3000:3000"
    environment:
      - ROOT_URL=localhost:3000/
      - RAILS_ENV=development
      - RACK_ENV=development
      - DATABASE_URL=postgres://bookmark_service:bookmark_service@postgres/bookmark_service
      - WEBPACKER_DEV_SERVER_HOST=webpack
      - ELASTICSEARCH_URL=elasticsearch:9200
    depends_on:
      - postgres
      - webpack

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
      environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
        - cluster.name=es-docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      cap_add:
        - IPC_LOCK
      volumes:
        - ./tmp/elasticsearch/data:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
