version: "3.9"

services:

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bookmark_service
      POSTGRES_PASSWORD: bookmark_service

  webpack:
    build: .
    command: ./bin/webpack-dev-server
    container_name: webpack
    volumes:
      - .:/bookmark_service
    ports:
      - "3035:3035"
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  bookmark_service:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: bookmark_service
    volumes:
      - .:/bookmark_service
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - DATABASE_URL=postgres://bookmark_service:bookmark_service@postgres/bookmark_service
      - WEBPACKER_DEV_SERVER_HOST=webpack
    depends_on:
      - postgres
      - webpack
